# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.1
maven_group = net.oxcodsnet.bl_accessories_layer
archives_name = bl_accessories_layer

# Minecraft properties
minecraft_version = 1.21.4
neoform_version = 1.21.4-20241203.161809

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.119.4+1.21.4
neoforge_version = 21.4.150

# WispForest Accessories
accessories_version=1.2.19-beta+1.21.4
owo_version=0.12.20+1.21.4
owo_neoforge_version=0.12.19-beta.3+1.21.4
cloth_config_version=17.0.144
beltborne_lanterns_version = 1.2.4
modmenu_version=13.0.3

# Mod metadata
mod_id=bl_accessories_layer
mod_name=Beltborne Lanterns: Accessories Layer
mod_name_web=BL: Accessories Layer
mod_description=Provides compatibility with the Accessories mod, allowing lanterns to be worn in the *Belt* slot.
mod_authors=0xCoDSnet
mod_homepage=https://github.com/0xCoDSnet
mod_sources=https://github.com/0xCoDSnet/Beltborne-Lanterns-Accessories-Layer
mod_license=Apache-2.0
