modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/0xCoDSnet/Beltborne-Lanterns-Accessories-Layer/issues"
license="${mod_license}"

[[mods]]
modId = "bl_accessories_layer"
version="${version}"
displayName="${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "assets/bl_accessories_layer/icon.png"

[[dependencies.bl_accessories_layer]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bl_accessories_layer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bl_accessories_layer]]
modId = "beltborne_lanterns"
type = "required"
versionRange = "[${beltborne_lanterns_version},)"
ordering = "NONE"
side = "BOTH"
